name: newsapp
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1


isar_version: &isar_version 3.1.0+1

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  isar: *isar_version
  isar_flutter_libs: *isar_version
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  injectable: ^2.5.0
  cached_network_image: ^3.4.1
  logger: ^2.5.0
  flutter_dotenv: ^5.2.1
  provider: ^6.1.2
  freezed_annotation: ^2.4.4
  infinite_scroll_pagination: ^4.1.0
  shimmer: ^3.0.0
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  isar_generator: *isar_version
  build_runner: ^2.4.13
  freezed: 2.5.2
  injectable_generator: 2.4.1
  json_serializable: ^6.8.0
  change_app_package_name: ^1.5.0


flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/fonts/
    - assets/img/

  fonts:
    - family: Figtree
      fonts:
        - asset: assets/fonts/Figtree-Black.ttf
          weight: 900
        - asset: assets/fonts/Figtree-Bold.ttf
        - asset: assets/fonts/Figtree-Light.ttf
        - asset: assets/fonts/Figtree-Medium.ttf
        - asset: assets/fonts/Figtree-Regular.ttf
